FIXED THE STREAM FETCH ISSUE!!!!!! HAVE TO EXPLICITLY TYPE QUERY/DOCUMENTSNAPSHOT AS Query/DocumentSnapshot<Map<String, dynamic>> IN THE STREAMTRANSFORMER Now throwing a nosuchmethoderror method[] was called on null when trying to create userdetails from membersdata but at least it is a different problem now